// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xffqdhuipnozkpomoxma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZnFkaHVpcG5vemtwb21veG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzg2NDQsImV4cCI6MjA2OTc1NDY0NH0.p6193AEJDMa_XHT5CCtXgQa5ktNngn97S1SMEyEwuBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});