// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbmevzgyrkciocithcwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpibWV2emd5cmtjaW9jaXRoY3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NjY5NTIsImV4cCI6MjA3MDA0Mjk1Mn0.2ji_ydL-h1ebtijHEEAE8XySP-7g6LZTGUniVDtvc_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});